In [1]:
import numpy as np
import pandas as pd
arr = [10, 20, 30, 40, 50, 60]
print("One-Dimensional Array:", arr)
print("\nIndexing:")
print("First element:", arr[0])
print("Third element:", arr[2])
print("Last element:", arr[-1])
print("\nSlicing:")
print("Elements from index 1 to 4:", arr[1:5])
print("\nStart, Stop and Step:")
print("Start=0, Stop=6, Step=2:", arr[0:6:2])
print("Start=1, Stop=6, Step=2:", arr[1:6:2])
print("\nReverse Array:")
print(arr[::-1])
arr2 = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print("\n\nTwo-Dimensional Array:")
print(arr2)
print("\nIndexing:")
print("First element:", arr2[0, 0])
print("Element at row 2, column 3:", arr2[1, 2])
print("\nSlicing:")
print("First two rows:")
print(arr2[0:2, :])
print("First two columns:")
print(arr2[:, 0:2])
print("\nStart, Stop and Step:")
print("Every alternate row:")
print(arr2[0:3:2])
print("Every alternate column:")
print(arr2[:, 0:3:2])
print("\nReverse 2-D Array:")
print(arr2[::-1, ::-1])
print("\n\nNumPy Operations:")
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])
print("Array A:", a)
print("Array B:", b)
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Sum of A:", np.sum(a))
print("Maximum of A:", np.max(a))
print("Minimum of A:", np.min(a))
print("Mean of A:", np.mean(a))
print("\n\nPandas Operations:")
data = {
    "Name": ["CHANDU", "KARTIK", "LEPU", "HEMU"],
    "Marks": [85, 92, 78, 88],
    "Age": [18, 19, 18, 20]
}
df = pd.DataFrame(data)
print("\nDataFrame:")
print(df)
print("\nMarks Column:")
print(df["Marks"])
print("\nFirst two rows:")
print(df.iloc[0:2])
print("\nAverage Marks:", df["Marks"].mean())
print("Highest Marks:", df["Marks"].max())
print("Lowest Marks:", df["Marks"].min())
print("\nData sorted by Marks:")
print(df.sort_values("Marks"))
print("\nStudents with marks greater than 80:")
print(df[df["Marks"] > 80])

One-Dimensional Array: [10, 20, 30, 40, 50, 60]

Indexing:
First element: 10
Third element: 30
Last element: 60

Slicing:
Elements from index 1 to 4: [20, 30, 40, 50]

Start, Stop and Step:
Start=0, Stop=6, Step=2: [10, 30, 50]
Start=1, Stop=6, Step=2: [20, 40, 60]

Reverse Array:
[60, 50, 40, 30, 20, 10]


Two-Dimensional Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Indexing:
First element: 10
Element at row 2, column 3: 60

Slicing:
First two rows:
[[10 20 30]
 [40 50 60]]
First two columns:
[[10 20]
 [40 50]
 [70 80]]

Start, Stop and Step:
Every alternate row:
[[10 20 30]
 [70 80 90]]
Every alternate column:
[[10 30]
 [40 60]
 [70 90]]

Reverse 2-D Array:
[[90 80 70]
 [60 50 40]
 [30 20 10]]


NumPy Operations:
Array A: [10 20 30 40 50]
Array B: [ 5 10 15 20 25]
Addition: [15 30 45 60 75]
Subtraction: [ 5 10 15 20 25]
Multiplication: [  50  200  450  800 1250]
Division: [2. 2. 2. 2. 2.]
Sum of A: 150
Maximum of A: 50
Minimum of A: 10
Mean of A: 30.0


Pandas Operations:

DataFrame: